# Rename this file to .streamlit/secrets.toml and add your actual credentials
# DO NOT commit the actual secrets.toml file to GitHub

# Supabase credentials
supabase_url = "YOUR_SUPABASE_URL"
supabase_key = "YOUR_SUPABASE_ANON_KEY"
